version: 0.2
phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Building static site"
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'  # Include all files from your repository
  base-directory: build  # If you have a build folder
  discard-paths: no

